### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GorlikItsMe** [morsisko/NosSplash#1]
when i use command
> python -m nosplash EWSF.EWS --extract
```
 is not an ELF
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Purge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nosplash\__main__.py", line 4, in <module>
    main()
  File "C:\Users\Purge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nosplash\nosplash.py", line 82, in main
    extract(content)
  File "C:\Users\Purge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nosplash\nosplash.py", line 23, in extract
    index = find_and_get_index(content, b"Picture.Data", index + 1)
NameError: name 'content' is not defined
```

**Comment by morsisko** [comment]
Hello, thanks for report, it should work fine now.

For that "is not an ELF" it looks like it is some lief package issue, but it's just a string printed out, no other consequences
https://github.com/lief-project/LIEF/issues/541
